version: "3"


services:

  v4l2rtspserver:
    image: mpromonet/v4l2rtspserver:latest
    devices:
      - /dev/video0
    networks:
      - cctv-net
    ports:
      - 8554:8554


networks:
  cctv-net:
